apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Logoffski/DevOps-Challenge.git
    targetRevision: HEAD
    path: deploy/main
  destination:
    server: https://kubernetes.default.svc
    namespace: main-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true